package com.autopilot.ai.controller;

import com.autopilot.ai.executor.PlaywrightExecutor;
import com.autopilot.ai.model.ExecutionPlan;
import com.autopilot.ai.model.ExecutionResult;
import com.autopilot.ai.model.ExecutionStep;
import com.autopilot.ai.parser.PlanParser;
import com.autopilot.ai.service.OllamaService;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
public class UIController {

    private final OllamaService ollamaService;
    private final PlanParser parser;
    private final PlaywrightExecutor executor;

    public UIController(
            OllamaService ollamaService,
            PlanParser parser,
            PlaywrightExecutor executor) {

        this.ollamaService = ollamaService;
        this.parser = parser;
        this.executor = executor;
    }

    @GetMapping("/")
    public String home() {

        System.out.println();
        System.out.println("==================================");
        System.out.println("AUTOPILOT AI UI LOADED");
        System.out.println("==================================");

        return "index";
    }

    @PostMapping("/generate")
    @ResponseBody
    public String generatePlan(
            @RequestParam String requirement) {

        System.out.println();
        System.out.println("==================================");
        System.out.println("AUTOPILOT AI AGENT STARTED");
        System.out.println("==================================");

        System.out.println();
        System.out.println("Requirement Received:");
        System.out.println(requirement);

        System.out.println();
        System.out.println("Step 1 : Connecting to Ollama...");

        String generatedPlan =
                ollamaService.generatePlan(requirement);

        System.out.println();
        System.out.println("Step 2 : AI Plan Generated");

        System.out.println("----------------------------------");
        System.out.println(generatedPlan);
        System.out.println("----------------------------------");

        return generatedPlan;
    }

    @PostMapping("/run")
    @ResponseBody
    public ExecutionResult runPlan(
            @RequestBody String jsonPlan) {

        try {

            System.out.println();
            System.out.println("Step 3 : Parsing Execution Plan...");

            ExecutionPlan plan =
                    parser.parse(jsonPlan);

            System.out.println(
                    "Step 4 : Plan Parsed Successfully");

            if (plan == null ||
                    plan.getSteps() == null ||
                    plan.getSteps().isEmpty()) {

                System.out.println(
                        "No steps generated by AI");

                return new ExecutionResult(
                        false,
                        "No execution steps generated by AI");
            }

            System.out.println();
            System.out.println("Generated Steps");
            System.out.println("----------------------------------");

            int stepNumber = 1;

            for (ExecutionStep step :
                    plan.getSteps()) {

                System.out.println(
                        "Step "
                                + stepNumber++
                                + " | Action="
                                + step.getAction()
                                + " | Locator="
                                + step.getLocator()
                                + " | Value="
                                + step.getValue());
            }

            System.out.println("----------------------------------");

            System.out.println();
            System.out.println(
                    "Step 5 : Executing Playwright...");

            ExecutionResult result =
                    executor.execute(plan);

            System.out.println();
            System.out.println(
                    "Step 6 : Execution Finished");

            System.out.println(
                    "Result : "
                            + result.getMessage());

            System.out.println();
            System.out.println("==================================");
            System.out.println("AUTOPILOT AI AGENT COMPLETED");
            System.out.println("==================================");

            return result;

        } catch (Exception e) {

            e.printStackTrace();

            return new ExecutionResult(
                    false,
                    "Agent Execution Failed : "
                            + e.getMessage());
        }
    }
}