package com.autopilot.ai.service;

import com.autopilot.ai.executor.PlaywrightExecutor;
import com.autopilot.ai.model.ExecutionPlan;
import com.autopilot.ai.model.ExecutionResult;
import com.autopilot.ai.model.ExecutionStep;
import com.autopilot.ai.parser.PlanParser;
import org.springframework.stereotype.Service;

@Service
public class AgentService {

    private final OllamaService ollamaService;
    private final PlanParser parser;
    private final PlaywrightExecutor executor;

    private String lastGeneratedPlan = "";

    public AgentService(
            OllamaService ollamaService,
            PlanParser parser,
            PlaywrightExecutor executor) {

        this.ollamaService = ollamaService;
        this.parser = parser;
        this.executor = executor;
    }

    public String getLastGeneratedPlan() {
        return lastGeneratedPlan;
    }

    public ExecutionResult runAgent(String requirement) {

        try {

            System.out.println();
            System.out.println("==================================");
            System.out.println("AGENT STARTED");
            System.out.println("Requirement : " + requirement);
            System.out.println("==================================");

            System.out.println("Step 1 : Calling Ollama...");

            String jsonPlan =
                    ollamaService.generatePlan(requirement);

            lastGeneratedPlan = jsonPlan;

            System.out.println();
            System.out.println("Step 2 : Plan Generated");
            System.out.println("----------------------------------");
            System.out.println(jsonPlan);
            System.out.println("----------------------------------");

            System.out.println("Step 3 : Parsing Plan...");

            ExecutionPlan plan =
                    parser.parse(jsonPlan);

            System.out.println("Step 4 : Plan Parsed Successfully");

            if (plan == null ||
                    plan.getSteps() == null ||
                    plan.getSteps().isEmpty()) {

                return new ExecutionResult(
                        false,
                        "No execution steps generated by AI");
            }

            System.out.println();
            System.out.println("Generated Steps");
            System.out.println("----------------------------------");

            int stepNumber = 1;

            for (ExecutionStep step : plan.getSteps()) {

                System.out.println(
                        "Step " + stepNumber++ +
                                " | Action=" + step.getAction() +
                                " | Locator=" + step.getLocator() +
                                " | Value=" + step.getValue());
            }

            System.out.println("----------------------------------");

            System.out.println("Step 5 : Executing Playwright...");

            ExecutionResult result =
                    executor.execute(plan);

            System.out.println();
            System.out.println("Step 6 : Execution Finished");
            System.out.println(
                    "Result : " + result.getMessage());

            System.out.println("==================================");

            return result;

        } catch (Exception e) {

            e.printStackTrace();

            return new ExecutionResult(
                    false,
                    "Agent Execution Failed : "
                            + e.getMessage());
        }
    }
}